name: Update subscriptions

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: '7.4'

      - name: Execute PHP script
        env:
          MY_CHANNELS: ${{ secrets.MY_CHANNELS }}
        run: |
          php bot.php
          git config credential.helper
